services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    mem_limit: 128m
    memswap_limit: 128m
    cpus: "0.05"
    networks:
      - e107_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8082:8080"
    mem_limit: 256m
    memswap_limit: 256m
    cpus: "0.15"
    restart: unless-stopped
    networks:
      - e107_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ubuntu/grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/grafana/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 512m
    cpus: "0.3"
    networks:
      - e107_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - /home/ubuntu/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /home/ubuntu/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=brainsecond.site
      - GF_SERVER_ROOT_URL=https://brainsecond.site/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - TZ=Asia/Seoul
    restart: unless-stopped
    mem_limit: 384m
    memswap_limit: 384m
    cpus: "0.1"
    networks:
      - e107_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    environment:
      - TZ=Asia/Seoul
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - /home/ubuntu/grafana/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    mem_limit: 256m
    memswap_limit: 256m
    cpus: "0.05"
    networks:
      - e107_net

networks:
  e107_net:
    external: true

volumes:
  grafana_data:
    external: true
  prometheus_data:
    external: true
